---
- name: Ensure jenkins directory on docker host
  file:
    state: directory
    owner: 1000
    group: 1000
    path: /data/jenkins

- name: Pull the latest official jenkins docker image
  docker_image:
    name: jenkins/jenkins:lts-alpine

- name: Create a container from the jenkins docker image
  docker_container:
    name: jenkins-master
    image: jenkins/jenkins:lts-alpine
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - /data/jenkins:/var/jenkins_home
    state: started
    recreate: no