---
- name: Create jenkins directory
  file:
    path: /var/www/jenkins
    state: directory
    mode: '0777'

- name: Write docker-compose.yml
  template: src=docker-compose.yaml dest=/var/www/jenkins/docker-compose.yaml

- name: Write Dockerfile
  template: src=Dockerfile dest=/var/www/jenkins/Dockerfile

- name: Build jenkins
  command: docker-compose up -d
  args:
    chdir: /var/www/jenkins

#---
#- name: Ensure jenkins directory on docker host
#  file:
#    state: directory
#    owner: 1000
#    group: 1000
#    path: /data/jenkins
#
#- name: Create jenkins Dockerfile directory
#  file:
#    state: directory
#    owner: 1000
#    group: 1000
#    path: /home/jenkins
#
#- name: Copy Dockerfile with owner and permissions
#  copy:
#    src: ../../../../jenkins/Dockerfile
#    dest: /home/jenkins/Dockerfile
#    mode: 0755
#
#- name: Copy docker-compose with owner and permissions
#  copy:
#    src: ../../../../jenkins/docker-compose.yml
#    dest: /home/jenkins/docker-compose.yml
#    mode: 0755
#
#- name: Build jenkins docker image
#  command: docker-compose up -d
#  args:
#    chdir: /home/jenkins