---
- name: Remove existing containers
  command: docker-compose down -v --remove-orphans
  args:
    chdir: /vagrant/PurpleClouds/ecorp

- name: Start the containers
  command: docker-compose up -d
  args:
    chdir: /vagrant/PurpleClouds/ecorp

- name: Run composer install inside the container
  command: docker-compose exec -T ecorp_purple_clouds_php composer install -n -v
  args:
    chdir: /vagrant/PurpleClouds/ecorp
    warn: no

- name: Run migrations inside container
  command: docker-compose exec -T ecorp_purple_clouds_php php bin/console doctrine:migrations:migrate -n
  args:
    chdir: /vagrant/PurpleClouds/ecorp
    warn: no