---
- name: Remove existing containers
  command: docker-compose down -v
  args:
    chdir: /vagrant/PurpleClouds/ecorp

- name: Start the containers
  command: docker-compose up -d
  args:
    chdir: /vagrant/PurpleClouds/ecorp

- name: Create .env file
  file:
    path: /vagrant/PurpleClouds/ecorp/.env
    state: touch
    content: |
      KERNEL_CLASS='App\Kernel'
      APP_SECRET='s$cretf0rt3st'
      SYMFONY_DEPRECATIONS_HELPER=999999
      DATABASE_URL=pgsql://mrrobot:root@127.0.0.1:5432/purpleclouds

- name: Run composer install inside the container
  command: docker exec -i ecorp_purple_clouds_php_1 bash -c "composer install -n -v"
  args:
    chdir: /vagrant/PurpleClouds/ecorp
