---
- name: Remove existing containers
  command: docker-compose down -v --remove-orphans
  args:
    chdir: /vagrant/PurpleClouds/ecorp

- name: Start the containers
  command: docker-compose up -d
  args:
    chdir: /vagrant/PurpleClouds/ecorp

- name: Create .env file
  file:
    path: /vagrant/PurpleClouds/ecorp/.env
    state: touch

- name: Add variables to .env
  blockinfile:
    path: /vagrant/PurpleClouds/ecorp/.env
    block: |
      APP_ENV=dev
      KERNEL_CLASS=App\Kernel
      APP_SECRET=s$cretf0rt3s
      SYMFONY_DEPRECATIONS_HELPER=999999
      DATABASE_URL=pgsql://mrrobot:root@ecorp_purple_clouds_postgres:5432/idp_purpleclouds

- name: Run composer install inside the container
  command: docker-compose exec -T ecorp_purple_clouds_php bash -c "composer install -n -v"
  args:
    chdir: /vagrant/PurpleClouds/ecorp

- name: Run migrations inside container
  command: docker-compose exec -T ecorp_purple_clouds_php bash -c "php bin/console doctrine:migrations:migrate -n"
  args:
    chdir: /vagrant/PurpleClouds/ecorp