---
- name: Remove existing containers
  command: docker-compose down -v --remove-orphans
  args:
    chdir: /vagrant/PurpleClouds/task-manager

- name: Start the containers
  command: docker-compose up -d
  args:
    chdir: /vagrant/PurpleClouds/task-manager

- name: Run composer install inside the container
  command: docker-compose exec -T task_manager_purple_clouds_php composer install -n -v
  args:
    chdir: /vagrant/PurpleClouds/task-manager