---
- name: Remove existing containers
  command: docker-compose down -v --remove-orphans
  args:
    chdir: /vagrant/PurpleClouds/task-manager

- name: Start the containers
  command: docker-compose up -d
  args:
    chdir: /vagrant/PurpleClouds/task-manager

- name: Create .env file
  file:
    path: /vagrant/PurpleClouds/task-manager/.env
    state: touch

- name: Add variables to .env
  blockinfile:
    path: /vagrant/PurpleClouds/task-manager/.env
    block: |
      APP_ENV=dev
      APP_SECRET=20a9c0ec5d3bbdeab34694b37d03168c

- name: Run composer install inside the container
  command: docker-compose exec -T purple-clouds-task-manager-php bash -c "composer install -n -v"
  args:
    chdir: /vagrant/PurpleClouds/task-manager