version: '3'
services:
  purple_clouds_php:
    image: "mkoziol/purpleclouds:${IMAGE_BUILD_TAG}"
    environment:
      APP_ENV: prod
    networks: ["default", "purple_clouds_network"]

  purple_clouds_nginx:
    image: nginx:stable
    ports:
      - "8001:8001"
    depends_on:
      - purple_clouds_php
    links:
      - purple_clouds_php
    volumes:
      - /var/www/PurpleClouds/blog/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks: ["default", "purple_clouds_network"]

networks:
  purple_clouds_network: {"external": {"name": "purple_clouds_network"}}