version: '3'
services:
  blog_purple_clouds_php:
    image: "mkoziol/purpleclouds:${IMAGE_BUILD_TAG}"
    environment:
      APP_ENV: prod
    networks: ["default", "purple_clouds_network"]

  blog_purple_clouds_nginx:
    image: nginx:stable
    ports:
      - "8001:8001"
    depends_on:
      - blog_purple_clouds_php
    links:
      - blog_purple_clouds_php
    volumes:
      - /var/www/PurpleClouds/blog/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks: ["default", "purple_clouds_network"]

  blog_purple_clouds_mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mrrobot
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - ./docker/mongodata:/data/db
    networks: ["default", "purple_clouds_network"]

  blog_purple_clouds_assets:
    image: "mkoziol/purpleclouds:${BLOG_NGINX_IMAGE_BUILD_TAG}"
    ports:
      - 8900:8900
    networks: ["default", "purple_clouds_network"]

networks:
  purple_clouds_network: {"external": {"name": "purple_clouds_network"}}
