---

- name: Ping the the hosts
  ping: ~

- name: Install aptitude
  apt:
    name: aptitude
    state: latest

- name: Update APT Reporistory
  apt:
    state: present
    update_cache: true
    force: yes
    allow_unauthenticated: yes

- name: Upgrade available packages
  apt:
    upgrade: dist