---

- name: Ping the the hosts
  ping: ~

- name: Install aptitude
  apt:
    name: aptitude
    state: latest

- name: Update APT Reporistory
  apt:
    state: latest
    update_cache: yes
    allow_unauthenticated: yes
    force: yes
    only_upgrade: yes

- name: Update and upgrade
  shell: apt-get update && apt-get upgrade
