version: '3'
services:
  purple_clouds_php:
    image: "mkoziol/purpleclouds:${IMAGE_BUILD_TAG}"
    links:
      - purple_clouds_postgres
    environment:
      KERNEL_CLASS: App\Kernel
      APP_SECRET: s$cretf0rt3s
      SYMFONY_DEPRECATIONS_HELPER: 999999
      DATABASE_URL: pgsql://mrrobot:root@77.55.222.35:5432/purpleclouds

  purple_clouds_nginx:
    image: nginx:stable
    ports:
      - 80:80
    depends_on:
      - purple_clouds_php
    links:
      - purple_clouds_php
    volumes:
      - /var/www/PurpleClouds/ecorp/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

  purple_clouds_postgres:
    image: postgres
    volumes:
      - ./docker/pgdata:/var/lib/postgresql
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: mrrobot
      POSTGRES_PASSWORD: root
      POSTGRES_DB: purpleclouds
