version: '3.9'
services:
  php:
    image: "${ECORP_PHP_IMAGE_BUILD_TAG}"
    links:
      - postgres
    networks: ["purple_clouds_network_external", "purple_clouds_network_internal"]

  nginx:
    image: nginx:stable
    ports:
      - "8000:8000"
    depends_on:
      - php
    volumes:
      - /var/www/PurpleClouds/ecorp/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks: ["purple_clouds_network_external", "purple_clouds_network_internal"]

  postgres:
    restart: always
    image: postgres:13.2-alpine
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: mrrobot
      POSTGRES_PASSWORD: root
      POSTGRES_DB: idp
    networks: ["purple_clouds_network_external", "purple_clouds_network_internal"]

  assets:
    image: "${ECORP_ASSETS_IMAGE_BUILD_TAG}"
    ports:
      - "8800:8800"
    networks: ["purple_clouds_network_external", "purple_clouds_network_internal"]
volumes:
  pgdata:

networks:
  purple_clouds_network_external: {"external": {"name": "purple_clouds_network_external"}}
  purple_clouds_network_internal: {"external": {"name": "purple_clouds_network_internal"}}
