version: '3'
services:
  ecorp_purple_clouds_php:
    image: "mkoziol/purpleclouds:${IMAGE_BUILD_TAG}"
    links:
      - ecorp_purple_clouds_postgres
    environment:
      KERNEL_CLASS: App\Kernel
      APP_SECRET: s$cretf0rt3s
      DATABASE_URL: pgsql://mrrobot:root@77.55.222.35:5432/purpleclouds
    networks: ["default", "purple_clouds_network"]

  ecorp_purple_clouds_nginx:
    image: nginx:stable
    ports:
      - "8000:8000"
    depends_on:
      - ecorp_purple_clouds_php
    links:
      - ecorp_purple_clouds_php
    volumes:
      - /var/www/PurpleClouds/ecorp/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks: ["default", "purple_clouds_network"]

  ecorp_purple_clouds_postgres:
    image: postgres
    volumes:
      - ./docker/pgdata:/var/lib/postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: mrrobot
      POSTGRES_PASSWORD: root
      POSTGRES_DB: purpleclouds
    networks: ["default", "purple_clouds_network"]

  ecorp_purple_clouds_assets:
    image: "mkoziol/purpleclouds:${ECORP_NGINX_IMAGE_BUILD_TAG}"
    ports:
      - "8800:8800"
    networks: ["default", "purple_clouds_network"]

networks:
  purple_clouds_network: {"external": {"name": "purple_clouds_network"}}
