version: '3'
services:
  ecorp_purple_clouds_php:
    image: "mkoziol/purpleclouds:${IMAGE_BUILD_TAG}"
    links:
      - ecorp_purple_clouds_postgres
    networks: ["purple_clouds_network_internal"]

  ecorp_purple_clouds_nginx:
    image: nginx:stable
    ports:
      - "8000:8000"
    depends_on:
      - ecorp_purple_clouds_php
    links:
      - ecorp_purple_clouds_php
    volumes:
      - /var/www/PurpleClouds/ecorp/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks: ["purple_clouds_network_internal"]

  ecorp_purple_clouds_postgres:
    image: postgres:10
    ports:
      - 5432:5432
    volumes:
      - ./docker/pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: mrrobot
      POSTGRES_PASSWORD: root
      POSTGRES_DB: idp_purpleclouds
    networks: ["purple_clouds_network_internal"]

  ecorp_purple_clouds_assets:
    image: "mkoziol/purpleclouds:${ECORP_NGINX_IMAGE_BUILD_TAG}"
    ports:
      - "8800:8800"
    networks: ["purple_clouds_network_internal"]

networks:
  purple_clouds_network_internal: {"external": {"name": "purple_clouds_network_internal"}}
