version: '3'
services:
  task_manager_purple_clouds_php:
    image: "mkoziol/purpleclouds:${IMAGE_BUILD_TAG}"
    networks: ["default", "purple_clouds_network"]

  task_manager_purple_clouds_nginx:
    image: nginx:latest
    ports:
      - "8002:8002"
    depends_on:
      - task_manager_purple_clouds_php
    volumes:
      - /var/www/PurpleClouds/task-manager/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks: ["default", "purple_clouds_network"]

networks:
  purple_clouds_network: {"external": {"name": "purple_clouds_network"}}
