---
blog_server_name: "blog.purpleclouds.local purpleclouds.local"
ecorp_server_name: "ecorp.purpleclouds.local"
task_manager_server_name: "task.purpleclouds.local"
wedding_server_name: "wedding.purpleclouds.local"

blog_nginx_docker: "blog_purple_clouds_nginx"
blog_php_docker: "blog_purple_clouds_php"
blog_assets: "blog_purple_clouds_assets"

ecorp_nginx_docker: "nginx"
ecorp_php_docker: "php"
ecorp_postgres_docker: "postgres"
ecorp_assets: "assets"

task_manager_nginx_docker: "task-manager_task_manager_purple_clouds_nginx_1"
task_manager_php_docker: "task-manager_task_manager_purple_clouds_php_1"

wedding_nginx_docker: "wedding_purple_clouds_nginx"
wedding_php_docker: "wedding_purple_clouds_php"
wedding_assets: "wedding_purple_clouds_assets"