version: '3.9'
services:
    traefik:
      image: traefik:v2.9.10
      command:
        - "--api.insecure=true"
        - "--providers.docker=true"
      volumes:
        - "/var/run/docker.sock:/var/run/docker.sock:ro"
      ports:
        - "80:80"
        - "8080:8080"
      restart: unless-stopped
      networks: ["mkoziol"]
networks:
    mkoziol: {"external": {"name": "mkoziol"}}
