---
- name: Create docker directory
  file:
    path: /var/www/PurpleClouds/blog/docker/nginx/
    state: directory
    mode: '0777'

- name: Write docker-compose.yml
  template: src=docker-compose.yml dest=/var/www/PurpleClouds/blog/docker-compose.yml

- name: Write nginx.conf
  template: src=nginx.conf dest=/var/www/PurpleClouds/blog/docker/nginx/nginx.conf