version: '3.8'
services:
  reverse_proxy:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NGINX_HTTP_PORT_NUMBER=80
      - NGINX_HTTPS_PORT_NUMBER=443
    networks: ["purple_clouds_network_external", "purple_clouds_network_internal"]

networks:
  purple_clouds_network_external: {"external": {"name": "purple_clouds_network_external"}}
  purple_clouds_network_internal: {"external": {"name": "purple_clouds_network_internal"}}
