---
- name: Create tmp/nginx directory
  file:
    path: /tmp/nginx
    state: directory
    mode: '0777'

- name: Copy nginx config template file
  template: src=default.conf dest=/tmp/nginx/default.conf

- name: Copy nginx docker-compose template file
  template: src=docker-compose.yml dest=/tmp/nginx/docker-compose.yml

- name: Copy SSL CRT file
  template: src=032A116F849F5BC6D0FF84A65B9CF7C5.crt dest=/tmp/nginx/032A116F849F5BC6D0FF84A65B9CF7C5.crt

- name: Copy SSL KEY file
  template: src=032A116F849F5BC6D0FF84A65B9CF7C5.key dest=/tmp/nginx/032A116F849F5BC6D0FF84A65B9CF7C5.key

- name: Copy nginx Dockerfile template file
  template: src=Dockerfile dest=/tmp/nginx/Dockerfile

- name: Remove existing containers
  command: docker-compose down -v --remove-orphans
  args:
    chdir: /tmp/nginx

- name: Start the containers
  command: docker-compose up -d -V --build
  args:
    chdir: /tmp/nginx

- name: Remove the template
  file: path=/tmp/nginx/default.conf state=absent

- name: Remove the template
  file: path=/tmp/nginx/docker-compose.yml state=absent

- name: Remove the template
  file: path=/tmp/nginx/Dockerfile state=absent

- name: Remove SSL CRT file
  file: path=/tmp/nginx/032A116F849F5BC6D0FF84A65B9CF7C5.crt state=absent

- name: Remove SSL KEY file
  file: path=/tmp/nginx/032A116F849F5BC6D0FF84A65B9CF7C5.key state=absent

- name: Remove directory
  file:
    path: /tmp/nginx
    state: absent
