---
- name: Create /var/www/PurpleClouds/nginx directory
  file:
    path: /var/www/PurpleClouds/nginx
    state: directory
    mode: '0777'

- name: Copy nginx config template file
  template: src=default.conf dest=/var/www/PurpleClouds/nginx/default.conf

- name: Copy nginx docker-compose template file
  template: src=docker-compose.yml dest=/var/www/PurpleClouds/nginx/docker-compose.yml

- name: Copy SSL CRT file
  template: src=purplecloud.pl/server.crt dest=/var/www/PurpleClouds/nginx/server.crt

- name: Copy SSL KEY file
  template: src=purplecloud.pl/server.key dest=/var/www/PurpleClouds/nginx/server.key

- name: Copy nginx Dockerfile template file
  template: src=Dockerfile dest=/var/www/PurpleClouds/nginx/Dockerfile

- name: Remove existing containers
  command: docker-compose down -v --remove-orphans
  args:
    chdir: /var/www/PurpleClouds/nginx

- name: Start the containers
  command: docker-compose up -d --build --force-recreate
  args:
    chdir: /var/www/PurpleClouds/nginx