---
- name: Create tmp/nginx directory
  file:
    path: /tmp/nginx
    state: directory
    mode: '0777'

- name: Copy nginx config template file
  template: src=default.conf dest=/tmp/nginx/default.conf

- name: Copy nginx docker-compose template file
  template: src=docker-compose.yml dest=/tmp/nginx/docker-compose.yml

- name: Copy nginx Dockerfile-dev template file
  template: src=Dockerfile-dev dest=/tmp/nginx/Dockerfile-dev

- name: Remove existing containers
  command: docker-compose down -v --remove-orphans
  args:
    chdir: /tmp/nginx

- name: Start the containers
  command: docker-compose up -d -V
  args:
    chdir: /tmp/nginx

- name: Remove the templates
  file: path=/tmp/nginx/default.conf state=absent

- name: Remove the templates
  file: path=/tmp/nginx/docker-compose.yml state=absent

- name: Remove the templates
  file: path=/tmp/nginx/Dockerfile-dev state=absent

- name: Remove directory
  file:
    path: /tmp/nginx
    state: absent
