---
- name: Install required system packages
  apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - python3-pip
      - virtualenv
      - python3-setuptools
    state: latest
    update_cache: true

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Configure Docker's upstream APT repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable
    update_cache: true

- name: Update apt and install docker-ce
  apt:
    name: docker-ce
    state: present
    update_cache: true

- name: Install pip3
  apt:
    name: python3-pip

- name: Install Docker Module for Python
  command: pip3 install docker

- name: Install pip3 docker-compose
  command: pip3 install docker-compose

- name: Install Virtualenv
  command: pip3 install virtualenv

- name: Create a network
  community.docker.docker_network:
    name: mkoziol