---
- name: Add Docker Group
  group: name=docker state=present

- name: Ensure docker users are added to the docker group.
  user:
    name: vagrant
    groups: docker
    append: true

- name: Install Docker's dependencies
  apt:
    name: "{{ docker__package_dependencies + docker__pip_dependencies }}"

- name: Add Docker's public GPG key to the APT keyring
  apt_key:
    id: "{{ docker__apt_key_id }}"
    url: "{{ docker__apt_key_url }}"

- name: Configure Docker's upstream APT repository
  apt_repository:
    repo: "{{ docker__apt_repository }}"
    update_cache: true

- name: Install Docker
  apt:
    name: "docker-{{ docker__edition }}"
    state: "{{docker__state}}"

- name: Install Virtualenv
  pip:
    name: "virtualenv"

- name: Install Python packages
  pip:
    name: >
      {{ item.name }}{% if item.version | d() %}=={{ item.version }}{% endif %}
    virtualenv: "{{ docker__pip_virtualenv }}"
    state: "{{ item.state | d('present') }}"
  loop: "{{ docker__default_pip_packages + docker__pip_packages }}"
  when: item.name | d()

- name: Symlink Python binary to /usr/local/bin/python-docker
  file:
    path: "/usr/local/bin/python-docker"
    src: "{{ docker__pip_virtualenv }}/bin/python"
    force: true
    state: "link"

- name: Symlink selected Python package binaries to /usr/local/bin
  file:
    path: "{{ item.path }}"
    src: "{{ item.src }}"
    force: true
    state: "link"
  loop: "{{ docker__default_pip_packages + docker__pip_packages }}"
  when:
    - item.state | d("present") != "absent"
    - item.path | d() and item.src | d()

- name: Install docker-py
  pip: name=docker-py version=1.9.0
