---
- name: Add Docker Group
  group: name=docker state=present

- name: Ensure docker users are added to the docker group.
  user:
    name: vagrant
    groups: docker
    append: true

- name: Install Docker's dependencies
  apt:
    name: "{{ docker__package_dependencies + docker__pip_dependencies }}"

- name: Add Docker's public GPG key to the APT keyring
  apt_key:
    id: "{{ docker__apt_key_id }}"
    url: "{{ docker__apt_key_url }}"

- name: Configure Docker's upstream APT repository
  apt_repository:
    repo: "{{ docker__apt_repository }}"
    update_cache: true

- name: Install Docker
  apt:
    name: "docker-{{ docker__edition }}"
    state: "{{docker__state}}"

- name: Install pip3
  apt:
    name: python3-pip

- name: Install pip3 docker-compose
  command: pip3 install docker-compose

- name: Install Virtualenv
  command: pip3 install virtualenv

- name: Create a network
  docker_network:
    name: '{{purple_clouds_docker_network_external}}'

- name: Create an internal network
  docker_network:
    name: '{{purple_clouds_docker_network_external}}'
    internal: true