---
- hosts: vb, prod
  become: true
  roles:
    - common
    - docker
    - ecorp-production
- import_playbook: ecorp-playbook.yml
- import_playbook: jenkins-playbook.yml
#- import_playbook: ansible-playbook.yml

