---
- hosts: vb, prod
  become: true
  roles:
    - common
    - docker
- import_playbook: ecorp-playbook.yml
- import_playbook: blog-playbook.yml
- import_playbook: ecorp-production-playbook.yml
- import_playbook: blog-production-playbook.yml
- import_playbook: jenkins-playbook.yml
- import_playbook: nginx-reverseproxy-playbook.yml
