version: '3.9'
services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
        - 8081:8081
        - 50000:50000
    volumes:
      - /var/www/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.http.routers.jenkins.rule=Host(`${jenkins_url:-jenkins.mateuszkoziol.local}`)"
    networks: ["mkoziol"]
networks:
    mkoziol: {"external": {"name": "mkoziol"}}
